### ISSUE TITLE
Improvements to visualization

### ISSUE THREAD

**Issue by nathanin** [nathanin/micron2#3]
- [ ] 🧠 visualize a group of experiments at-once. Use the shifted scatter plot strategy. When a selection is made, detect the slide and load the appropriate image region

- [x] ⚡ add a configurable amount of "compression" to the images by downsampling. Multiply the `hx` and `hy` parameters accordingly to display in the correct dimensions.

- [ ] 📓 basic annotation functionality

- [ ] 🔍  "inside/outside" tool, basically an analysis pane that can select cells in a group, and cells not in the group, and run a test for association of a particular cell type with group membership. Select spatial regions, or other groups of cells, allow any annotation/grouping/boolean vector over cells to be the membership. 

- [x] In the channel pane we want a list of N channels, with name, color and an automatically chosen saturation value:
- [x] The name should be clickable, and the color should be customizable
- [x]  There should be an update image button, in order to avoid redrawing a potentially large image with every small change to the channel color configuration.
- [ ] ❓ load in preconfigured sets of channels / colors associated with a project. I.e. 4 lineage markers, 4 immune cell markers, Tcell subtype markers.
- [x] Allow / toggle segmentation overlay (+ segmentation color) in the image panel.
- [x] tie scrolling in scatter plot in with scrolling in the image
- [ ] Add graph support to the spatial dot-panel, allowing visualization of graph connections between nearby cells.
- [ ] Disable axis scrolling?
- [x] ~~Fix plot layout ratios.~~
- [ ] Add niche cohabitation as a heatmap
- [ ] Add channel correlation heatmap within focused cells (allowed to be selected in the in-situ scatter pane) (+ spatial correlation of stains ?)
- [ ] Allow choosing annotation to display in scatter pane
- [x] ~~Remove scatter gate pane and controls -- it's not ready yet~~
- [x] join scatter and image plots 510a4c10e947685d7e94c0cdfd6370d0c3519f82
- [x] allow changing scatter dot size 510a4c10e947685d7e94c0cdfd6370d0c3519f82
- [ ] Bundle channel color selector somehow in a scrolling box, or split off into another page if possible, or as a file that gets written to/read from? what other options?
- [x] fix image blending strategy to avoid clipping e9230e491fd6feed37a5f18a562b6030be63358b
- [ ] Unset the box select tool after selecting a region of image. Often box-select --> scatter refreshes, but box-select is still active, so you go to zoom/pan and end up selecting a new area.
- [x] Option to hide all non-focused dots, instead of drawing them as gray. The many gray dots are distracting.
- [ ] Continuous valued dot colors from adata variables
- [ ] Clear image button that flushes image data so only the scatter plot is left
